### PR TITLE
fix(issuer): improve the toTokens function for raisedamount

### PR DESCRIPTION
**Pull request by sajclarke**
**Please make sure the following boxes are checked before submitting your Pull Request:**

- [x] I've added this PR's link to its Asana task(s)
- [ ] If this PR adds new code that is not going to change in the near future, it includes unit tests to cover it.

### CODE REVIEW

**Comment by RafaelVidaurre** [comment]
This looks good implementation-wise. My concern is that exponential notation doesn't have much meaning for the user. Maybe even adding a line-break is better?

**Comment by RafaelVidaurre** [comment]
Let's discuss on the task @sajclarke

**Comment by RafaelVidaurre** [comment]
A discussed @sajclarke let's just wrap the numbers

**Comment by RafaelVidaurre** [comment]
I'm seeing some changes unrelated to the `toTokens` function. Where's the text wrapping btw?

**Comment by sajclarke** [comment]
> I'm seeing some changes unrelated to the `toTokens` function. Where's the text wrapping btw?

Strange. May be a result of merging after such a long time. The RaisedAmount container already includes text wrapping. I'll close this and submit a new PR

**Pull request closed without merging**
