### PR TITLE
Feature/offchain rework

### PR DESCRIPTION
**Pull request by monitz87**
FINALLY!!!  🎉🎉🎉🎉🎉🎉

The offchain rework is here.

This PR refactors the offchain app almost completely and fixes some potential security issues in the API:

- Transaction emails were triggered from the issuer app, now they trigger from listeners on the blockchain
- Transaction email bodies were being sent to the API by the issuer app, allowing malicious users to forge polymath emails

The whole app is documented in the wiki: [Polymath Offchain](https://github.com/PolymathNetwork/polymath-apps/wiki/Package:-Polymath-Offchain)

Please review as best you can (I know it's a LOT to take in) and let me know what you think

### CODE REVIEW

**Comment by RafaelVidaurre** [comment]
@monitz87 Awesome!!!!

I think you forgot to update the snapshots, since those are failing ;p
```
href="https://kovan.etherscan.io/address/0xffffffffffffffff"
    +                 href="https://local.etherscan.io/address/0xffffffffffffffff"
```

**Comment by monitz87** [comment]
> @monitz87 Awesome!!!!
> 
> I think you forgot to update the snapshots, since those are failing ;p
> 
> ```
> href="https://kovan.etherscan.io/address/0xffffffffffffffff"
>     +                 href="https://local.etherscan.io/address/0xffffffffffffffff"
> ```
> Or is this related to some missing env var?



> @monitz87 Awesome!!!!
> 
> I think you forgot to update the snapshots, since those are failing ;p
> 
> ```
> href="https://kovan.etherscan.io/address/0xffffffffffffffff"
>     +                 href="https://local.etherscan.io/address/0xffffffffffffffff"
> ```
> Or is this related to some missing env var?

Yeah, it depends on WEB3_NETWORK_NAME

**Comment by RafaelVidaurre** [comment]
@monitz87 ok, I'd add an `.env.test` file with whatever values the tests might care about. These can almost always be just mock values, but the important thing is that we have to override the actual env vars in runtime.

Maybe even better is to just mock the env in the tests that depend on it?

**Comment by monitz87** [comment]
Yeah, makes sense, I didn't consider that. I think I'll go the .env.test route. Seems less obscure to me

**Comment by monitz87** [comment]
💪

**Pull request merged**
